### CA Fuels Generation mix
#     Report on the distribution of electricity generated by different fuel sources
#     This file generates the dashboards ui and handles server-side processing
#
#     By Patrick Rogers, California Research Bureau
#       May 2023
#
#     Uses the following Packages
#       {shiny}
#       {shinydashboard}
#       {leaflet}
#       {DT}
#       {here}

# Load Packages
library(shiny)
library(shinydashboard)
library(leaflet)
library(DT)

# Inits
setwd(here::here())

# Load Sourcefiles
source(here::here("load_data.R"))

# Custom Functions ####

# Find best metric label for electrical units
get_metric_label <- function(n){
  if((n %/% 10^12) >= 1) { return(list(unit = "EWh", denom = 10^12)) }
  if((n %/% 10^9) >= 1) { return(list(unit = "PWh", denom = 10^9)) }
  if((n %/% 10^6) >= 1) { return(list(unit = "TWh", denom = 10^6)) }
  if((n %/% 10^3) >= 1) { return(list(unit = "GWh", denom = 10^3)) }
  # Else
  return(list(unit = "MWh", denom = 1))
}

# Clean ValueBox Text
clean_sum_text <- function(data){
  total <- sum(data, na.rm = TRUE)
  unit_denom <- get_metric_label(total)
  
  val <- paste(round(total/unit_denom$denom, digits = 2), unit_denom$unit)
  
  return(val)
}

# Plotting Functions
# Energy Mix Barplot ####
energy_mix_barplot <- function(year){
  included_indices <- qfer_monthly_combined$Year==year
  aggregated_data <- aggregate(qfer_monthly_combined$NetMWh[included_indices],
                               by=list(Type = qfer_monthly_combined$Type[included_indices]),
                               FUN=sum)
  
  unit_denom <- get_metric_label(max(aggregated_data$x))
  
  par(pty = "m", plt=c(0.1, 1, 0.1, 1), omd=c(0.1,0.9,0.1,0.9))
  
  barplot(x ~ Type,
          data = aggregated_data,
          horiz = TRUE,
          xaxt="n",
          xlab="",
          ylab="",
          las=2)
  
  aty <- seq(par("xaxp")[1], par("xaxp")[2], (par("xaxp")[2] - par("xaxp")[1])/par("xaxp")[3])
  axis(1, at=aty, labels=paste(format(aty/unit_denom$denom, scientific=FALSE), unit_denom$unit) , hadj=0.9, cex.axis=1, las=1)
}

# Energy mix locations ####
energy_mix_locations <- function(data, year){
  #aggregate(NetMWh ~ Type + State, data = qfer_monthly_combined[qfer_monthly_combined$Year==input$generation_by_fuel_year,], FUN = "sum")
  aggregated_data <- aggregate(NetMWh ~ Type + State, data = data[data$Year==year,], FUN = "sum")

  
  aggregated_data$Percentage <- 1
  for(type in unique(aggregated_data$Type)){
    i <- which(aggregated_data$Type == type)
    aggregated_data$Percentage[i] <- aggregated_data$NetMWh[i]/sum(aggregated_data$NetMWh[i])
  }
  
  aggregated_data$Percentage <- paste0(round(aggregated_data$Percentage*100, digits=2), "%")
  aggregated_data$NetMWh <- format(aggregated_data$NetMWh, big.tick=",")
  aggregated_data <- aggregated_data[order(aggregated_data$Type, aggregated_data$State),]
  row.names(aggregated_data) <- NULL
  
  return(aggregated_data)
}

# Energy Mix Trendlines ####
energy_mix_trendlines <- function(data, startyear, endyear, type){
  included_indices <- data$Year>=startyear & data$Year<=endyear
  aggregated_data <- aggregate(data$NetMWh[included_indices],
                               by=list(Type = data$Type[included_indices],
                                       Year = data$Year[included_indices]),
                               FUN=sum)
  # Handle "relative" plot option
  if(type == "Relative"){
    for(type in unique(aggregated_data$Type)){
      aggregated_data$x[aggregated_data$Type == type] <- aggregated_data$x[aggregated_data$Type == type] - aggregated_data$x[(aggregated_data$Type) == type & (aggregated_data$Year == min(aggregated_data$Year))]
    }
  }
  
  unit_denom <- get_metric_label(max(aggregated_data$x))
  
  par(pty = "m", plt=c(0.05, .95, 0.1, .95), omd=c(.025,1,0,1), mar=c(5,4,4,5))
  
  types <- unique(aggregated_data$Type)
  line_width <- 3
  colors <- palette(hcl.colors(11, "viridis"))
  
  plot(x ~ Year, data = aggregated_data[aggregated_data$Type == types[1],],
       type = "l",
       xaxt="n",
       yaxt="n",
       xlab="",
       ylab="",
       xlim=c(min(aggregated_data$Year),max(aggregated_data$Year) + (max(aggregated_data$Year)-min(aggregated_data$Year))/5),
       ylim=c(min(0, min(aggregated_data$x)),max(aggregated_data$x)),
       lwd = line_width,
       bty = "l",
       col = colors[1])
  
  
  for(i in 2:length(unique(aggregated_data$Type))){
    lines(x ~ Year, data = aggregated_data[aggregated_data$Type == types[i],],
          lwd = line_width,
          col = colors[i])
  }
  
  text(x = max(aggregated_data$Year),
       y = aggregated_data$x[aggregated_data$Year == max(aggregated_data$Year)],
       labels = aggregated_data$Type[aggregated_data$Year == max(aggregated_data$Year)],
       pos = 4)
  
  atx <- seq(min(aggregated_data$Year), max(aggregated_data$Year), (max(aggregated_data$Year) - min(aggregated_data$Year))/5)
  aty <- seq(par("yaxp")[1], par("yaxp")[2], (par("yaxp")[2] - par("yaxp")[1])/par("yaxp")[3])
  
  axis(1, at=atx, labels=atx, hadj=0.9, cex.axis=1, las=1)
  axis(2, at=aty, labels=paste(format(aty/unit_denom$denom, scientific=FALSE), unit_denom$unit), hadj=0.9, cex.axis=1, las=1)
}

# Build UI ####
sidebar <- dashboardSidebar(
  sidebarMenu(
    menuItem(
      "Home",
      tabName = "home",
      icon = icon("house")
    ),
    menuItem(
      "Fuel Types",
      tabName = "fuels",
      icon = icon("charging-station")
    ),
    menuItem(
      "Data",
      tabName = "data",
      icon = icon("table-list")
    ),
    menuItem(
      "Additional Info",
      tabName = "info",
      icon = icon("circle-info")
    )
  ))

body <- dashboardBody(a(id="top"), 
                      tags$head(
                        # Note the wrapping of the string in HTML()
                        tags$style(HTML("
      /* CSS styles get tested here, before being moved to external for production. */"))
                      ),
                      
                      tabItems(
                        # Home ####
                        tabItem(tabName = "home",
                                h2(paste(max(qfer_monthly_combined$Year), "California Electricity Generation System Dashboard")),
                                fluidRow(
                                  # Top level dashboard boxes and map of generation units
                                  valueBox(format(length(unique(generating_units$CECPlantID[generating_units$Retired_Plant == 0])), big.mark = ","), "Active Generation Facilities", icon = icon("industry"), width = 3),
                                  valueBox(clean_sum_text(qfer_monthly_combined$NetMWh[qfer_monthly_combined$Year==max(qfer_monthly_combined$Year)]), "Electricity Generated", icon = icon("bolt"), width = 3),
                                  valueBox(clean_sum_text(qfer_monthly_combined$NetMWh[(qfer_monthly_combined$Year==max(qfer_monthly_combined$Year)) & (qfer_monthly_combined$Renewable == 1)]), "Electricity from Renewables", icon = icon("envira"), width = 3),
                                  valueBox(paste(format(round(sum(qfer_monthly_combined$CO2_pounds, na.rm = TRUE)/(2000*1000000000), digits=1), big.mark = ","), "billion tons"), paste0("CO2 Emissions from Generation"), icon = icon("temperature-3"), width = 3),
                                  
                                  box(
                                    checkboxGroupInput("generator_types", label = h4("Fuel Types"),
                                                       choices = c("Biomass","Coal","Geothermal",
                                                                   "Hydro (Large and Small)","Natural Gas",
                                                                   "Nuclear","Oil","Petroleum Coke","Solar",
                                                                   "Waste Heat","Wind"),
                                                       selected = c("Biomass","Coal","Geothermal",
                                                                    "Hydro (Large and Small)","Natural Gas",
                                                                    "Nuclear","Oil","Petroleum Coke","Solar",
                                                                    "Waste Heat","Wind")),
                                    
                                    
                                    checkboxGroupInput("generator_status", label = h4("Status"),
                                                       choices = c("Active","Retired"),
                                                       selected = c("Active")),
                                    
                                    actionButton(inputId = "map_selectall", label = "Select/Deselect All"),
                                    
                                    title = "",
                                    width=3
                                  ),
                                  
                                  box(
                                    leafletOutput("generator_locs", width = "100%", height="50vh"),
                                    
                                    title = "Electricity Generating Units in California",
                                    footer = "Note: Some facilities have multiple generating units.",
                                    width = 9
                                  )
                                )),
                        
                        # Fuel Types ####
                        tabItem(tabName = "fuels",
                                h2("California Electricity Generation System Fuel Types"),
                                fluidRow(
                                  # Main Fuel Type Barplot
                                  box(
                                    selectInput("generation_by_fuel_year",
                                                "Year",
                                                choices = max(qfer_monthly_combined$Year):min(qfer_monthly_combined$Year),
                                                selected = max(qfer_monthly_combined$Year)),
                                    
                                    width = 3
                                  ),
                                  
                                  box(
                                    title = textOutput("generation_by_fuel_title", inline = TRUE),
                                    plotOutput("generation_by_fuel"),
                                    
                                    DT::dataTableOutput("data_fueltype_location"),
                                    
                                    width = 9
                                  )
                                ),
                                
                                fluidRow(
                                  # Fuel Type Trend Lines
                                  box(
                                    radioButtons(inputId = "trendline_type",
                                                 label = "Type of Comparison",
                                                 choices = c("Absolute", "Relative"),
                                                 selected = "Absolute"),
                                    
                                    checkboxGroupInput("trendline_fueltypes", label = h4("Fuel Types"),
                                                       choices = c("Biomass","Coal","Geothermal",
                                                                   "Hydro (Large and Small)","Natural Gas",
                                                                   "Nuclear","Oil","Petroleum Coke","Solar",
                                                                   "Waste Heat","Wind"),
                                                       selected = c("Biomass","Coal","Geothermal",
                                                                    "Hydro (Large and Small)","Natural Gas",
                                                                    "Nuclear","Oil","Petroleum Coke","Solar",
                                                                    "Waste Heat","Wind")),
                                    
                                    actionButton(inputId = "trendline_selectall", label = "Select/Deselect All"),
                                    width = 3
                                  ),
                                  
                                  box(
                                    plotOutput("generation_by_fuel_trendlines"),
                                    
                                    sliderInput("year_range",
                                                "Years:",
                                                min = min(qfer_monthly_combined$Year),
                                                max = max(qfer_monthly_combined$Year),
                                                value = c(max(qfer_monthly_combined$Year)-9, max(qfer_monthly_combined$Year)),
                                                step = 1,
                                                sep = ""),
                                    
                                    width = 9
                                  )
                                )),
                        
                        # Data ####
                        tabItem(tabName = "data",
                                h2("California Electricity Generation System Data"),
                                fluidRow(
                                  # Nav Row
                                  box(title = "Contents",
                                      tags$ul(
                                        tags$li(
                                          a("Fuel Types Data", href="#fueltypes")),
                                        tags$li(
                                          a(paste0(max(qfer_monthly_combined$Year), " Operators"), href="#operators")),
                                        tags$li(
                                          a(paste0(max(qfer_monthly_combined$Year), " Generating Units", href="#genunits")))),
                                      width = 3
                                  ),
                                  
                                  # Fuel Type Data
                                  box(
                                    title = "Fuel Types Data (Units in Net MWh)",
                                    a(id="fueltypes"),
                                    DT::dataTableOutput("data_fueltype"),
                                    a("[Back to Top]", href="#top"),
                                    width = 12
                                  ),
                                  
                                  # Operator Data
                                  box(
                                    title = paste(max(qfer_monthly_combined$Year), "Operators (Units in Net MWh)"),
                                    a(id="operators"),
                                    DT::dataTableOutput("data_operator"),
                                    a("[Back to Top]", href="#top"),
                                    width = 12
                                  ),
                                  
                                  # Generating Units Data
                                  box(
                                    title = paste(max(qfer_monthly_combined$Year), "Generating Units"),
                                    a(id="genunits"),
                                    DT::dataTableOutput("data_genunits"),
                                    a("[Back to Top]", href="#top"),
                                    width=12
                                  )
                                )),
                        
                        # Additional Info ####
                        tabItem(tabName = "info",
                                h2("Additional Info"),
                                fluidRow(
                                  box(title = "About the CA Electricity Generation System Dashboard",
                                      
                                      p("This dashboard was produced by Patrick Rogers at the ",
                                        tags$a(href="https://www.library.ca.gov/crb/", "California Research Bureau", .noWS = "outside"),
                                        ", a state agency dedicated to providing nonpartisan and confidential public policy research for the Governor’s Office and the State Legislature. This tool utilizes ",
                                        tags$a(href="https://www.energy.ca.gov/data-reports/energy-almanac/california-electricity-data", "California Energy Commission Electricity Data", .noWS = "outside"),
                                        ", which serves as a valuable resource for understanding the state's energy landscape. The data used includes ",
                                        tags$a(href="https://www.energy.ca.gov/files/webqfer-source-files", "Quarterly Fuel and Energy Report (QFER)", .noWS = "outside"),
                                        " data tables, which provide detailed information on fuel types, electricity generation, and consumption patterns. Additionally, location data is incorporated from the ",
                                        tags$a(href="https://cecgis-caenergy.opendata.arcgis.com/datasets/CAEnergy::california-power-plants/explore", "California Power Plants", .noWS = "outside"),
                                        " dataset, which offers insights into the capacity, location, and operational details of power plants across the state."),
                                      width = 12
                                  ),
                                  
                                  box(title = "Links and Resources",
                                      p("To learn about California's electricity generation system, here are some good resources to start with:",
                                        tags$ul(tags$li(tags$strong("California Energy Commission (CEC)"), " - The CEC is the primary agency responsible for collecting and analyzing energy data in California. Their website offers a wealth of information on electricity generation, including reports, studies, and data on renewable energy, fossil fuels, and more. Visit their website at:", tags$a(href="https://www.energy.ca.gov/", "https://www.energy.ca.gov/")),
                                                tags$li(tags$strong("California Energy Almanac"), " - This online resource provides a comprehensive overview of California's energy sector. It covers electricity generation, consumption, policies, and more. The almanac is regularly updated and offers detailed insights into the state's energy landscape:", tags$a(href="http://energyalmanac.ca.gov/", "http://energyalmanac.ca.gov/")),
                                                tags$li(tags$strong("California Renewables Portfolio Standard (RPS)"), " - California has an ambitious renewable energy target. The RPS requires utilities to procure a certain percentage of their electricity from renewable sources. Exploring information about the RPS can give you insights into the state's renewable energy efforts. You can find information on the CEC's website:", tags$a(href="https://www.energy.ca.gov/renewables/portfoliorequirements/", "https://www.energy.ca.gov/renewables/portfoliorequirements/")),
                                                tags$li(tags$strong("California Independent System Operator (CAISO)"), " - CAISO is the organization responsible for managing the flow of electricity across California's grid. Their website provides information on the state's electricity market, grid operations, and renewable integration. You can find reports, data, and market information on their website:", tags$a(href="https://www.caiso.com/", "https://www.caiso.com/")),
                                                tags$li(tags$strong("California ISO Today"), " - This website provides real-time data on California's electricity grid, including information on energy supply, demand, and renewable generation. It offers live data and charts that can give you insights into the state's electricity system:", tags$a(href="https://www.caiso.com/TodaysOutlook/Pages/default.aspx", "https://www.caiso.com/TodaysOutlook/Pages/default.aspx")),
                                                tags$li(tags$strong("California Public Utilities Commission (CPUC)"), " - The CPUC regulates the state's investor-owned electric utilities. They oversee utility planning, rates, and policies. Their website contains information on electricity procurement, utility plans, and energy programs:", tags$a(href="https://www.cpuc.ca.gov/", "https://www.cpuc.ca.gov/"))
                                        )),
                                      
                                      
                                      width = 12)
                                ))
                      ))

ui <- dashboardPage(dashboardHeader(title = ""),
                    sidebar,
                    body)

# Build Server ####

server <- function(input, output, session) {
  # Home Tab ####
  # Observer to Handle Select/Deselect All for Map
  observeEvent(input$map_selectall, {
    if (length(input$generator_types) == 11 &
        length(input$generator_status) == 2){
      updateSelectInput(session, "generator_types", selected = character(0))
      updateSelectInput(session, "generator_status", selected = character(0))
    } else {
      updateSelectInput(session, "generator_types", selected = c("Biomass", "Coal", "Geothermal", "Hydro (Large and Small)", "Natural Gas", "Nuclear", "Oil", "Petroleum Coke", "Solar", "Waste Heat", "Wind"))
      updateSelectInput(session, "generator_status", selected = c("Active", "Retired"))
    }
  })
  
  # Filtering by fuel types for Map
  generating_units_filtered <- reactive ({
    generating_units[(generating_units$Type %in% input$generator_types) &
                       (generating_units$Status %in% input$generator_status),]
  })
  
  # Draw Map
  output$generator_locs <- renderLeaflet({
    leaflet(data = generating_units_filtered()) |>
      addTiles() |>
      addMarkers(lng = ~longitude, lat = ~latitude,
                 clusterOptions = markerClusterOptions(),
                 popup = ~popuphtml) |>
      setMaxBounds(min(generating_units$longitude), min(generating_units$latitude), max(generating_units$longitude), max(generating_units$latitude))
  })
  
  # Fuel Types Tab ####
  # Main Fuel Type BarPlot
  output$generation_by_fuel <- renderPlot({
    energy_mix_barplot(
      year = input$generation_by_fuel_year)
  })
  
  # Main Fuel Type Barplot Title
  output$generation_by_fuel_title <- renderText({ paste0("CA Electric Generation by Fuel Type (", input$generation_by_fuel_year, ")") })
  
  output$data_fueltype_location <- DT::renderDataTable(server = FALSE,
                                              {
                                                DT::datatable(energy_mix_locations(data = qfer_monthly_combined, year = input$generation_by_fuel_year), rownames = FALSE, extensions = "Buttons",
                                                              options = list(pageLength = 10, scrollX = TRUE,
                                                                             dom = "lfrtBip",
                                                                             buttons = list("copy",
                                                                                            list(extend="csv", filename="CA Electricity Generation by Type of Fuel and State"),
                                                                                            list(extend="excel", filename="CA Electricity Generation by Type of Fuel and State"))))
                                              })
  
  
  
  # Fuel Type Trendlines
  # Observer to Handle Select/Deselect All for Trendlines
  observeEvent(input$trendline_selectall, {
    message("trendline selectall presssed")
    if (length(input$trendline_fueltypes) == 11){
      updateSelectInput(session, "trendline_fueltypes", selected = character(0))
    } else {
      updateSelectInput(session, "trendline_fueltypes", selected = c("Biomass", "Coal", "Geothermal", "Hydro (Large and Small)", "Natural Gas", "Nuclear", "Oil", "Petroleum Coke", "Solar", "Waste Heat", "Wind"))
    }
  })
  
  # Filtering by fuel types for trendlines
  energy_mix_trend_filtered <- reactive({
    qfer_monthly_combined[(qfer_monthly_combined$Type %in% input$trendline_fueltypes) &
                            (qfer_monthly_combined$Year>=input$year_range[1] & qfer_monthly_combined$Year<=input$year_range[2]),
                          c("NetMWh", "Type", "Year")]
  })
  
  # Draw Trendlines
  output$generation_by_fuel_trendlines <- renderPlot({
    energy_mix_trendlines(
      data = energy_mix_trend_filtered(),
      startyear = input$year_range[1],
      endyear = input$year_range[2],
      type = input$trendline_type)
  })
  # Data Tab ####
  # Fuel Types Data
  fuel_types <- aggregate(NetMWh ~ Type + Year, data = qfer_monthly_combined, FUN = "sum")
  colnames <- c("Year", unique(fuel_types$Type))
  fuel_types <- reshape(fuel_types, direction = "wide", idvar = "Year", timevar = "Type")
  colnames(fuel_types) <- colnames
  fuel_types <- fuel_types[order(fuel_types$Year, decreasing = TRUE),]
  row.names(fuel_types) <- NULL
  
  output$data_fueltype <- DT::renderDataTable(server = FALSE,
                                              {
                                                DT::datatable(fuel_types, rownames = FALSE, extensions = "Buttons",
                                                              options = list(pageLength = 10, scrollX = TRUE,
                                                                             dom = "lfrtBip",
                                                                             buttons = list("copy",
                                                                                            list(extend="csv", filename="CA Electricity Generation by Type of Fuel"),
                                                                                            list(extend="excel", filename="CA Electricity Generation by Type of Fuel"))))
                                              })
  
  # Operators Data
  operators <- aggregate(NetMWh ~ OperatorCompanyID + Type, data = qfer_monthly_combined[qfer_monthly_combined$Year==max(qfer_monthly_combined$Year),], FUN = "sum")
  colnames <- c("OperatorCompanyID", unique(operators$Type))
  operators <- reshape(operators, direction = "wide", idvar = "OperatorCompanyID", timevar = "Type")
  colnames(operators) <- colnames
  operators <- operators[order(operators$OperatorCompanyID),]
  row.names(operators) <- NULL
  
  output$data_operator <- DT::renderDataTable(server = FALSE,
                                              
                                              {
                                                DT::datatable(operators, rownames = FALSE, extensions = "Buttons",
                                                              options = list(pageLength = 10, scrollX = TRUE,
                                                                             dom = "lfrtBip",
                                                                             buttons = list("copy",
                                                                                            list(extend="csv", filename=paste0("CA ", max(qfer_monthly_combined$Year), " Electricity Operators")),
                                                                                            list(extend="excel", filename=paste0("CA ", max(qfer_monthly_combined$Year)," Electricity Operators")))))
                                              })
  
  # Generating Units Data
  genunits <- aggregate(NetMWh ~ PlantName + Unit + OperatorCompanyID + Type, data = qfer_monthly_combined[qfer_monthly_combined$Year == max(qfer_monthly_combined$Year) & qfer_monthly_combined$Status == "Active", ], FUN = "sum")
  genunits <- genunits[order(genunits$PlantName),]
  row.names(genunits) <- NULL
  
  output$data_genunits <- DT::renderDataTable(server = FALSE,
                                              {
                                                DT::datatable(genunits, rownames = FALSE, extensions = "Buttons",
                                                              options = list(pageLength = 10, scrollX = TRUE,
                                                                             dom = "lfrtBip",
                                                                             buttons = list("copy",
                                                                                            list(extend="csv", filename=paste0("CA ", max(qfer_monthly_combined$Year), " Generating Units")),
                                                                                            list(extend="excel", filename=paste0("CA ", max(qfer_monthly_combined$Year), " Generating Units")))))
                                              })
}

# Run! ####
shinyApp(ui, server)