### CA Fuels Generation mix
#     Report on the distribution of electricity generated by different fuel sources
#     This file loads and cleans the data for presentation
#
#     By Patrick Rogers, California Research Bureau
#       May 2023

# Load Packages
library(htmltools)

# Load Data ####

# CA Energy Commission Quarterly Fuel and Energy Data
energy_types <- read.csv(file = "https://www.energy.ca.gov/filebrowser/download/4565")
generating_units <- read.csv(file = "https://www.energy.ca.gov/filebrowser/download/4569")
qfer_monthly <- read.csv(file = "https://www.energy.ca.gov/filebrowser/download/4567")
power_plants <- read.csv("https://cecgis-caenergy.opendata.arcgis.com/datasets/CAEnergy::california-power-plants.csv?outSR=%7B%22latestWkid%22%3A4269%2C%22wkid%22%3A4269%7D")

# Clean and Merge
energy_types <- energy_types[,!(colnames(energy_types) == "Description")]

power_plants <- power_plants[,c("X", "Y", "CECPlantID", "PlantName", "Retired_Plant", "OperatorCompanyID", "County")]
colnames(power_plants)[1:2] <- c("longitude", "latitude")

generating_units <- merge(generating_units, energy_types, by.x = "PriEnergySource", by.y = "Source", all.x = TRUE)
generating_units <- merge(generating_units, power_plants, by.x = "CECPlantID", by.y = "CECPlantID", all.x = TRUE)

# Create status variable
generating_units$Status <- "Active"
generating_units$Status[generating_units$Retired_Plant == 1] <- "Retired"

# Remove Duplicated Generating Units
j <- which(duplicated(generating_units[,c("State", "CECPlantID", "Unit")]))

if(length(j) > 0){
  generating_units <- generating_units[-j,]
}

# Fix missing plant name
generating_units$PlantName[which(generating_units$CECPlantID == "W0470")] <- "Voyager Wind I, LLC"

# Some qfer_monthly stats are duplicated
qfer_monthly <- qfer_monthly[!duplicated(qfer_monthly),]

# Final merge
qfer_monthly_combined <- merge(qfer_monthly, generating_units, by = c("State","CECPlantID","Unit"), all.x = TRUE)

# if(nrow(qfer_monthly_combined) != nrow(qfer_monthly)){
#   warning("Merging resulted in adding or dropping of data")
# } else {
#   message("Merge successful")
# }

# Calculate C02 Estimate
qfer_monthly_combined$CO2_pounds <- qfer_monthly_combined$PriMMBtu * qfer_monthly_combined$EIA_Pounds_CO2_per_MMBtu



# Set up map-specific data
# Getting some NAs in generating_units
generating_units <- generating_units[!is.na(generating_units$latitude),]

# Generate text for map pop-ups
generating_units$popuphtml <- paste0("<strong>", generating_units$PlantName, "</strong>", br(),
                                     br(),
                                     "<em>Unit:</em> ", generating_units$Unit, br(),
                                     "<em>Fuel:</em> ", generating_units$Description, br(),
                                     "<em>Status:</em> ", generating_units$Status, br(),
                                     br(),
                                     "<em>Operator:</em> ", generating_units$OperatorCompanyID
)